const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { DatabaseSync } = require('node:sqlite');

const {
  buildLegacyPlatformReconciliationSql,
  buildPostgresCompatibleMigrationSql,
} = require('../scripts/postgres-platform-schema-upgrade');
const {
  buildSqliteCompatibleMigrationSql,
  stripLegacyHybridDefaultsFromSqliteDatabase,
} = require('../scripts/platform-schema-upgrade');

test('buildPostgresCompatibleMigrationSql converts SQLite datetime and boolean defaults', () => {
  const sql = [
    'CREATE TABLE "Example" (',
    '  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,',
    '  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,',
    '  "enabled" BOOLEAN NOT NULL DEFAULT 1,',
    '  "disabled" BOOLEAN DEFAULT 0',
    ');',
  ].join('\n');

  const rendered = buildPostgresCompatibleMigrationSql(sql);

  assert.match(rendered, /"id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(rendered, /"createdAt" TIMESTAMP\(3\) NOT NULL DEFAULT CURRENT_TIMESTAMP/);
  assert.match(rendered, /"enabled" BOOLEAN NOT NULL DEFAULT TRUE/);
  assert.match(rendered, /"disabled" BOOLEAN DEFAULT FALSE/);
});

test('buildLegacyPlatformReconciliationSql includes representative legacy backfills', () => {
  const sql = buildLegacyPlatformReconciliationSql();

  assert.match(
    sql,
    /ALTER TABLE IF EXISTS public\."platform_users" ADD COLUMN IF NOT EXISTS "primaryEmail" TEXT;/,
  );
  assert.match(
    sql,
    /ALTER TABLE IF EXISTS public\."platform_users" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;/,
  );
  assert.match(
    sql,
    /UPDATE public\."platform_verification_tokens"\s+SET "purpose" = COALESCE\("purpose", NULLIF\("tokenType", ''\)\)/,
  );
  assert.match(
    sql,
    /ALTER TABLE IF EXISTS public\."platform_billing_invoices" ALTER COLUMN "amountCents" SET DEFAULT 0;/,
  );
  assert.match(
    sql,
    /ALTER TABLE IF EXISTS public\."ControlPlaneAgent" ALTER COLUMN "role" DROP DEFAULT;/,
  );
  assert.match(
    sql,
    /ALTER TABLE IF EXISTS public\."ControlPlaneSyncRun" ALTER COLUMN "scope" DROP DEFAULT;/,
  );
});

test('buildSqliteCompatibleMigrationSql rewrites ADD COLUMN IF NOT EXISTS for missing columns', () => {
  const migrationSql = 'ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;';
  const rendered = buildSqliteCompatibleMigrationSql(migrationSql, {
    databaseFilePath: path.join(os.tmpdir(), `codex-missing-${process.pid}.db`),
  });

  assert.equal(
    rendered.trim(),
    'ALTER TABLE "platform_users" ADD COLUMN "passwordHash" TEXT;',
  );
});

test('buildSqliteCompatibleMigrationSql skips ADD COLUMN IF NOT EXISTS when the column already exists', async (t) => {
  const dbPath = path.join(os.tmpdir(), `codex-platform-upgrade-${process.pid}-${Date.now()}.db`);
  const db = new DatabaseSync(dbPath);
  db.exec('CREATE TABLE "platform_users" ("id" TEXT PRIMARY KEY, "passwordHash" TEXT);');
  db.close();
  t.after(() => {
    fs.rmSync(dbPath, { force: true });
  });

  const migrationSql = 'ALTER TABLE "platform_users" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;';
  const rendered = buildSqliteCompatibleMigrationSql(migrationSql, {
    databaseFilePath: dbPath,
  });

  assert.match(rendered, /skipped existing column platform_users\.passwordHash/);
});

test('buildSqliteCompatibleMigrationSql strips legacy hybrid control-plane defaults', () => {
  const migrationSql = [
    'CREATE TABLE "ControlPlaneAgent" (',
    '  "role" TEXT NOT NULL DEFAULT \'hybrid\',',
    '  "scope" TEXT NOT NULL DEFAULT \'sync_execute\'',
    ');',
  ].join('\n');

  const rendered = buildSqliteCompatibleMigrationSql(migrationSql, {
    databaseFilePath: path.join(os.tmpdir(), `codex-default-strip-${process.pid}.db`),
  });

  assert.doesNotMatch(rendered, /DEFAULT 'hybrid'/);
  assert.doesNotMatch(rendered, /DEFAULT 'sync_execute'/);
  assert.match(rendered, /"role" TEXT NOT NULL,/);
  assert.match(rendered, /"scope" TEXT NOT NULL/);
});

test('stripLegacyHybridDefaultsFromSqliteDatabase scrubs tracked sqlite artifacts in place', async (t) => {
  const dbPath = path.join(os.tmpdir(), `codex-runtime-defaults-${process.pid}-${Date.now()}.db`);
  const db = new DatabaseSync(dbPath);
  db.exec([
    'CREATE TABLE "ControlPlaneAgent" (',
    '  "id" TEXT PRIMARY KEY,',
    '  "role" TEXT NOT NULL DEFAULT \'hybrid\',',
    '  "scope" TEXT NOT NULL DEFAULT \'sync_execute\'',
    ');',
    'INSERT INTO "ControlPlaneAgent" ("id", "role", "scope") VALUES (\'agent-1\', \'delivery\', \'execute_only\');',
  ].join('\n'));
  db.close();
  t.after(() => {
    fs.rmSync(dbPath, { force: true });
  });

  const result = stripLegacyHybridDefaultsFromSqliteDatabase(dbPath);

  assert.equal(result.changed, true);
  assert.deepEqual(result.updatedTables, ['ControlPlaneAgent']);

  const verifyDb = new DatabaseSync(dbPath, { readOnly: true });
  const schemaRow = verifyDb.prepare(`
    SELECT sql
    FROM sqlite_master
    WHERE type = 'table' AND name = 'ControlPlaneAgent'
  `).get();
  const dataRow = verifyDb.prepare('SELECT "role", "scope" FROM "ControlPlaneAgent" WHERE "id" = ?').get('agent-1');
  verifyDb.close();

  assert.equal(dataRow.role, 'delivery');
  assert.equal(dataRow.scope, 'execute_only');
  assert.doesNotMatch(String(schemaRow?.sql || ''), /DEFAULT 'hybrid'/);
  assert.doesNotMatch(String(schemaRow?.sql || ''), /DEFAULT 'sync_execute'/);
});
