'use strict';

function createAdminRouteHandlersRuntime(deps) {
  const {
    createServerRegistryService,
    createAgentRegistryService,
    createSyncIngestionService,
    createPlatformServerConfigService,
    createAdminEntityPostRoutes,
    createAdminConfigPostRoutes,
    createAdminPublicRoutes,
    createAdminGetRoutes,
    createAdminAuthPostRoutes,
    createAdminCommerceDeliveryPostRoutes,
    createAdminPortalPostRoutes,
    createAdminPlatformPostRoutes,
    createAdminAuditRoutes,
    createAdminRouteRuntime,
    createPlatformApiKey,
    listPlatformApiKeys,
    listPlatformAgentRuntimes,
    recordPlatformAgentHeartbeat,
    revokePlatformApiKey,
    rotatePlatformApiKey,
    getPlatformTenantById,
    emitPlatformEvent,
    sendJson,
    requiredString,
    asInt,
    claimSupportTicket,
    closeSupportTicket,
    tryNotifyTicket,
    createBountyForUser,
    cancelBountyForUser,
    createServerEvent,
    updateServerEvent,
    startServerEvent,
    finishServerEvent,
    joinServerEvent,
    reviewRaidRequest,
    createRaidWindow,
    createRaidSummary,
    bindSteamLinkForUser,
    removeSteamLink,
    upsertPlayerAccount,
    grantVipForUser,
    revokeVipForUser,
    createRedeemCodeForAdmin,
    deleteRedeemCodeForAdmin,
    resetRedeemCodeUsageForAdmin,
    createPunishmentEntry,
    revokeWelcomePackClaimForAdmin,
    clearWelcomePackClaimsForAdmin,
    addKillsForUser,
    addDeathsForUser,
    addPlaytimeForUser,
    queueLeaderboardRefreshForAllGuilds,
    getTenantFeatureAccess,
    buildTenantProductEntitlements,
    parseStringArray,
    getAuthTenantId,
    buildAdminEditableEnvPatch,
    buildAdminEditableEnvApplySummary,
    updateEnvFile,
    resolveAdminEditableRootEnvFilePath,
    resolveAdminEditablePortalEnvFilePath,
    recordAdminSecuritySignal,
    consumeAdminActionRateLimit,
    getClientIp,
    upsertAdminUserInDb,
    revokeSessionsForUser,
    buildClearSessionCookie,
    restartManagedRuntimeServices,
    config,
    resolveScopedTenantId,
    upsertPlatformTenantConfig,
    tryServeAdminStaticAsset,
    tryServeStaticScumIcon,
    sendText,
    sendHtml,
    isAuthorized,
    getAuthContext,
    getLoginHtml,
    getOwnerLoginHtml,
    getTenantLoginHtml,
    getOwnerConsoleHtml,
    getTenantConsoleHtml,
    getDashboardHtml,
    getPersistenceStatus,
    getPublicPersistenceStatus,
    getDeliveryMetricsSnapshot,
    ensurePlatformApiKey,
    readJsonBody,
    getTenantQuotaSnapshot,
    getPlatformPublicOverview,
    getPlatformAnalyticsOverview,
    findPlanById,
    getPackageCatalogSummary,
    getFeatureCatalogSummary,
    resolvePackageForPlan,
    verifyPlatformApiKey,
    SSO_DISCORD_ACTIVE,
    cleanupDiscordOauthStates,
    buildDiscordAuthorizeUrl,
    getDiscordRedirectUri,
    exchangeDiscordOauthCode,
    fetchDiscordProfile,
    fetchDiscordGuildMember,
    listDiscordGuildRolesFromClient,
    resolveMappedMemberRole,
    getAdminSsoRoleMappingSummary,
    SSO_DISCORD_GUILD_ID,
    SSO_DISCORD_DEFAULT_ROLE,
    discordOauthStates,
    createSession,
    buildSessionCookie,
    invalidateSession,
    authenticateTenantUser,
    consumeTenantBootstrapToken,
    resolveTenantSessionAccessContext,
    resolveAdminSessionAccessContext,
    prisma,
    sendDownload,
    consumeTransientDownload,
    ensureRole,
    ensurePortalTokenAuth,
    getSessionId,
    hasFreshStepUp,
    hasValidSession,
    filterRowsByTenantScope,
    jsonReplacer,
    getAdminPermissionMatrixSummary,
    buildRoleMatrix,
    listAdminPermissionMatrix,
    listAdminSecurityEvents,
    buildAdminSecurityEventExportRows,
    buildAdminSecurityEventCsv,
    buildSecretRotationReport,
    buildSecretRotationCsv,
    listAdminSessions,
    listAdminUsersFromDb,
    buildControlPanelSettings,
    buildCommandRegistry,
    getRuntimeSupervisorSnapshot,
    getAdminRestoreState,
    listAdminRestoreHistory,
    buildTenantDiagnosticsBundle,
    buildTenantDiagnosticsCsv,
    buildTenantSupportCaseBundle,
    buildTenantSupportCaseCsv,
    buildDeliveryLifecycleReport,
    buildDeliveryLifecycleCsv,
    buildTenantDonationOverview,
    buildTenantModuleOverview,
    getPlatformPermissionCatalog,
    getPlanCatalog,
    listPersistedPackageCatalog,
    buildTenantActorAccessSummary,
    buildTenantRoleMatrix,
    getPlatformOpsState,
    getPlatformAutomationState,
    getAutomationConfig,
    getPlatformTenantConfig,
    listPlatformTenants,
    listPlatformTenantConfigs,
    listTenantStaffMemberships,
    listServerEvents,
    getParticipants,
    listRaidActivitySnapshot,
    listKillFeedEntries,
    listPlatformSubscriptions,
    listPlatformLicenses,
    listBillingInvoices,
    listBillingPaymentAttempts,
    getBillingProviderConfigSummary,
    listPlatformWebhookEndpoints,
    listMarketplaceOffers,
    reconcileDeliveryState,
    listRestartPlans,
    listRestartExecutions,
    clampMetricsWindowMs,
    parseMetricsSeriesKeys,
    getCurrentObservabilitySnapshot,
    getAdminRequestLogMetrics,
    listAdminRequestLogs,
    buildObservabilityCsv,
    buildObservabilityExportPayload,
    openLiveStream,
    listItemIconCatalog,
    listWikiWeaponCatalog,
    getWikiWeaponCatalogMeta,
    listManifestItemCatalog,
    getManifestItemCatalogMeta,
    listShopItems,
    filterShopItems,
    listUserPurchases,
    normalizePurchaseStatus,
    getPlayerDashboard,
    listActiveBountiesForUser,
    listFilteredDeliveryQueue,
    listFilteredDeliveryDeadLetters,
    getDeliveryRuntimeStatus,
    listScumAdminCommandCapabilities,
    listAdminCommandCapabilityPresets,
    getDeliveryCommandOverride,
    getDeliveryDetailsByPurchaseCode,
    listAdminNotifications,
    listKnownPurchaseStatuses,
    listAllowedPurchaseTransitions,
    buildAdminDashboardCards,
    listPlayerAccounts,
    buildAdminSnapshot,
    listAdminBackupFiles,
    ADMIN_WEB_2FA_ACTIVE,
    SESSION_COOKIE_NAME,
    SESSION_COOKIE_PATH,
    SESSION_COOKIE_SAMESITE,
    SESSION_SECURE_COOKIE,
    SESSION_COOKIE_DOMAIN,
    SESSION_TTL_MS,
    SESSION_IDLE_TIMEOUT_MS,
    SESSION_MAX_PER_USER,
    SESSION_BIND_USER_AGENT,
    ADMIN_WEB_STEP_UP_ENABLED,
    ADMIN_WEB_STEP_UP_TTL_MS,
    ADMIN_WEB_ALLOW_TOKEN_SENSITIVE_MUTATIONS,
    getLoginRateLimitState,
    recordLoginAttempt,
    getUserByCredentials,
    ADMIN_WEB_2FA_SECRET,
    ADMIN_WEB_2FA_WINDOW_STEPS,
    verifyTotpCode,
    setCoinsExact,
    creditCoins,
    debitCoins,
    addShopItemForAdmin,
    updateShopItemForAdmin,
    setShopItemPriceForAdmin,
    setShopItemStatusForAdmin,
    deleteShopItemForAdmin,
    updatePurchaseStatusForActor,
    parseDeliveryItemsBody,
    enqueuePurchaseDeliveryByCode,
    retryDeliveryNow,
    retryDeliveryNowMany,
    retryDeliveryDeadLetter,
    retryDeliveryDeadLetterMany,
    removeDeliveryDeadLetter,
    cancelDeliveryJob,
    previewDeliveryCommands,
    getDeliveryPreflightReport,
    simulateDeliveryPlan,
    setDeliveryCommandOverride,
    sendTestDeliveryCommand,
    saveAdminCommandCapabilityPreset,
    getAdminCommandCapabilityPresetById,
    deleteAdminCommandCapabilityPreset,
    testScumAdminCommandCapability,
    runRentBikeMidnightReset,
    getRentBikeRuntime,
    updateScumStatusForAdmin,
    getStatus,
    redeemCodeForUser,
    requestRentBikeForUser,
    prepareTransientDownload,
    createAdminBackup,
    previewAdminBackupRestore,
    restoreAdminBackup,
    publishAdminLiveUpdate,
    createTenant,
    createPackageCatalogEntry,
    inviteTenantStaff,
    updateTenantStaffRole,
    revokeTenantStaffMembership,
    createSubscription,
    deletePackageCatalogEntry,
    createCheckoutSession,
    updateInvoiceStatus,
    updatePaymentAttempt,
    updateSubscriptionBillingState,
    issuePlatformLicense,
    acceptPlatformLicenseLegal,
    createPlatformWebhookEndpoint,
    dispatchPlatformWebhookEvent,
    scheduleRestartPlan,
    createMarketplaceOffer,
    runPlatformMonitoringCycle,
    runPlatformAutomationCycle,
    acknowledgeAdminNotifications,
    clearAdminNotifications,
    updatePackageCatalogEntry,
    buildAuditDatasetService,
    buildAuditExportPayloadService,
    buildAuditCsvService,
    listAuditPresetsService,
    saveAuditPresetService,
    deleteAuditPresetService,
  } = deps;

  const serverRegistryService = createServerRegistryService();
  const agentRegistryService = createAgentRegistryService({
    createPlatformApiKey,
    listPlatformApiKeys,
    listPlatformAgentRuntimes,
    recordPlatformAgentHeartbeat,
    revokePlatformApiKey,
    rotatePlatformApiKey,
    getPlatformTenantById,
    recordAdminSecuritySignal,
  });
  const syncIngestionService = createSyncIngestionService({
    emitPlatformEvent,
  });

  const {
    createServer,
    createServerDiscordLink,
    listServerLinks: listPlatformServerLinks,
    listServerRegistry: listPlatformServerRegistry,
  } = serverRegistryService;
  const {
    activateAgent: activatePlatformAgent,
    createAgentProvisioningToken: createPlatformAgentProvisioningToken,
    createAgentToken: createPlatformAgentToken,
    listAgentRegistry: listPlatformAgentRegistry,
    listManagedAgentCredentials: listPlatformAgentCredentials,
    listManagedAgentDevices: listPlatformAgentDevices,
    listProvisioningTokens: listPlatformAgentProvisioningTokens,
    recordSession: recordPlatformAgentSession,
    registerAgent: registerPlatformAgent,
    revokeManagedAgentDevice: revokePlatformAgentDevice,
    revokeManagedRuntime: revokePlatformAgentRuntime,
    revokeProvisioningToken: revokePlatformAgentProvisioningToken,
    revokeAgentToken: revokePlatformAgentToken,
    rotateAgentToken: rotatePlatformAgentToken,
  } = agentRegistryService;
  const { ingestPayload: ingestPlatformAgentSync } = syncIngestionService;
  const platformServerConfigService = createPlatformServerConfigService({
    listServerRegistry: listPlatformServerRegistry,
  });
  const {
    getServerConfigCategory,
    getServerConfigJob,
    getServerConfigWorkspace,
    listServerConfigJobs,
    listServerConfigBackups,
    createServerConfigSaveJob,
    createServerConfigApplyJob,
    createServerConfigRollbackJob,
    createServerBotActionJob,
    claimNextServerConfigJob,
    completeServerConfigJob,
    retryServerConfigJob,
    upsertServerConfigSnapshot,
  } = platformServerConfigService;

  const handleAdminEntityPostRoute = createAdminEntityPostRoutes({
    sendJson,
    requiredString,
    asInt,
    claimSupportTicket,
    closeSupportTicket,
    tryNotifyTicket,
    createBountyForUser,
    cancelBountyForUser,
    createServerEvent,
    updateServerEvent,
    startServerEvent,
    finishServerEvent,
    joinServerEvent,
    reviewRaidRequest,
    createRaidWindow,
    createRaidSummary,
    bindSteamLinkForUser,
    removeSteamLink,
    upsertPlayerAccount,
    grantVipForUser,
    revokeVipForUser,
    createRedeemCodeForAdmin,
    deleteRedeemCodeForAdmin,
    resetRedeemCodeUsageForAdmin,
    createPunishmentEntry,
    revokeWelcomePackClaimForAdmin,
    clearWelcomePackClaimsForAdmin,
    addKillsForUser,
    addDeathsForUser,
    addPlaytimeForUser,
    queueLeaderboardRefreshForAllGuilds,
    emitPlatformEvent,
    getTenantFeatureAccess,
    buildTenantProductEntitlements,
  });

  const handleAdminConfigPostRoute = createAdminConfigPostRoutes({
    sendJson,
    requiredString,
    parseStringArray,
    getAuthTenantId,
    buildControlPanelEnvPatch: buildAdminEditableEnvPatch,
    buildControlPanelEnvApplySummary: buildAdminEditableEnvApplySummary,
    updateEnvFile,
    getRootEnvFilePath: resolveAdminEditableRootEnvFilePath,
    getPortalEnvFilePath: resolveAdminEditablePortalEnvFilePath,
    recordAdminSecuritySignal,
    getClientIp,
    upsertAdminUserInDb,
    revokeSessionsForUser,
    buildClearSessionCookie,
    restartManagedRuntimeServices,
    config,
    resolveScopedTenantId,
    getPlatformTenantById,
    upsertPlatformTenantConfig,
    getTenantFeatureAccess,
    buildTenantProductEntitlements,
  });

  const handleAdminPublicRoute = createAdminPublicRoutes({
    tryServeAdminStaticAsset,
    tryServeStaticScumIcon,
    sendJson,
    sendText,
    sendHtml,
    isAuthorized,
    getAuthContext,
    getLoginHtml,
    getOwnerLoginHtml,
    getTenantLoginHtml,
    getOwnerConsoleHtml,
    getTenantConsoleHtml,
    getDashboardHtml,
    getPersistenceStatus,
    getPublicPersistenceStatus,
    getDeliveryMetricsSnapshot,
    ensurePlatformApiKey,
    requiredString,
    readJsonBody,
    getTenantQuotaSnapshot,
    getTenantFeatureAccess,
    getPlatformPublicOverview,
    getPlatformAnalyticsOverview,
    getPackageCatalog: getPackageCatalogSummary,
    getFeatureCatalog: getFeatureCatalogSummary,
    recordPlatformAgentHeartbeat,
    verifyPlatformApiKey,
    activatePlatformAgent,
    registerPlatformAgent,
    recordPlatformAgentSession,
    ingestPlatformAgentSync,
    upsertServerConfigSnapshot,
    claimNextServerConfigJob,
    completeServerConfigJob,
    reconcileDeliveryState,
    dispatchPlatformWebhookEvent,
    ssoDiscordActive: SSO_DISCORD_ACTIVE,
    cleanupDiscordOauthStates,
    buildDiscordAuthorizeUrl,
    getDiscordRedirectUri,
    exchangeDiscordOauthCode,
    fetchDiscordProfile,
    fetchDiscordGuildMember,
    listDiscordGuildRolesFromClient,
    resolveMappedMemberRole,
    getAdminSsoRoleMappingSummary,
    ssoDiscordGuildId: SSO_DISCORD_GUILD_ID,
    ssoDiscordDefaultRole: SSO_DISCORD_DEFAULT_ROLE,
    setDiscordOauthState: (state, payload) => discordOauthStates.set(state, payload),
    hasDiscordOauthState: (state) => discordOauthStates.has(state),
    deleteDiscordOauthState: (state) => discordOauthStates.delete(state),
    getClientIp,
    recordAdminSecuritySignal,
    consumeAdminActionRateLimit,
    createSession,
    buildSessionCookie,
    buildClearSessionCookie,
    invalidateSession,
    authenticateTenantUser,
    consumeTenantBootstrapToken,
    resolveTenantSessionAccessContext,
    resolveAdminSessionAccessContext,
  });

  const handleAdminGetRoute = createAdminGetRoutes({
    prisma,
    sendJson,
    sendDownload,
    readJsonBody,
    consumeTransientDownload,
    ensureRole,
    ensurePortalTokenAuth,
    getAuthContext,
    getAuthTenantId,
    getSessionId,
    hasFreshStepUp,
    hasValidSession,
    resolveScopedTenantId,
    filterRowsByTenantScope,
    requiredString,
    asInt,
    jsonReplacer,
    getAdminSsoRoleMappingSummary,
    getAdminPermissionMatrixSummary,
    buildRoleMatrix,
    listAdminPermissionMatrix,
    listAdminSecurityEvents,
    buildAdminSecurityEventExportRows,
    buildAdminSecurityEventCsv,
    buildSecretRotationReport,
    buildSecretRotationCsv,
    listAdminSessions,
    listAdminUsersFromDb,
    buildControlPanelSettings,
    buildCommandRegistry,
    getRuntimeSupervisorSnapshot,
    getAdminRestoreState,
    listAdminRestoreHistory,
    getPlatformAnalyticsOverview,
    buildTenantDiagnosticsBundle,
    buildTenantDiagnosticsCsv,
    buildTenantSupportCaseBundle,
    buildTenantSupportCaseCsv,
    buildDeliveryLifecycleReport,
    buildDeliveryLifecycleCsv,
    buildTenantDonationOverview,
    buildTenantModuleOverview,
    getPlatformPublicOverview,
    getPlatformPermissionCatalog,
    getPlanCatalog,
    getPackageCatalog: getPackageCatalogSummary,
    listPersistedPackageCatalog,
    getFeatureCatalog: getFeatureCatalogSummary,
    getTenantFeatureAccess,
    buildTenantProductEntitlements,
    buildTenantActorAccessSummary,
    buildTenantRoleMatrix,
    getPlatformOpsState,
    getPlatformAutomationState,
    getPlatformAutomationConfig: getAutomationConfig,
    getPlatformTenantConfig,
    getTenantQuotaSnapshot,
    listPlatformTenants,
    listPlatformTenantConfigs,
    listTenantStaffMemberships,
    listServerEvents,
    getParticipants,
    listRaidActivitySnapshot,
    listKillFeedEntries,
    listPlatformSubscriptions,
    listPlatformLicenses,
    listBillingInvoices,
    listBillingPaymentAttempts,
    getBillingProviderConfigSummary,
    listPlatformApiKeys,
    listPlatformWebhookEndpoints,
    listPlatformAgentRuntimes,
    listPlatformServerRegistry,
    listPlatformServerLinks,
    listServerConfigJobs,
    getServerConfigWorkspace,
    getServerConfigCategory,
    listServerConfigBackups,
    listRestartPlans,
    listRestartExecutions,
    listPlatformAgentRegistry,
    listPlatformAgentProvisioningTokens,
    listPlatformAgentDevices,
    listPlatformAgentCredentials,
    listPlatformAgentSessions: deps.listControlPlaneAgentSessions,
    listPlatformSyncRuns: deps.listControlPlaneSyncRuns,
    listPlatformSyncEvents: deps.listControlPlaneSyncEvents,
    listMarketplaceOffers,
    reconcileDeliveryState,
    clampMetricsWindowMs,
    parseMetricsSeriesKeys,
    getCurrentObservabilitySnapshot,
    getAdminRequestLogMetrics,
    listAdminRequestLogs,
    buildObservabilityCsv,
    buildObservabilityExportPayload,
    openLiveStream,
    listItemIconCatalog,
    listWikiWeaponCatalog,
    getWikiWeaponCatalogMeta,
    listManifestItemCatalog,
    getManifestItemCatalogMeta,
    listShopItems,
    filterShopItems,
    listUserPurchases,
    normalizePurchaseStatus,
    getPlayerDashboard,
    listActiveBountiesForUser,
    listFilteredDeliveryQueue,
    listFilteredDeliveryDeadLetters,
    getDeliveryRuntimeStatus,
    listScumAdminCommandCapabilities,
    listAdminCommandCapabilityPresets,
    getDeliveryCommandOverride,
    getDeliveryDetailsByPurchaseCode,
    listAdminNotifications,
    listKnownPurchaseStatuses,
    listAllowedPurchaseTransitions,
    buildAdminDashboardCards,
    listPlayerAccounts,
    buildAdminSnapshot,
    listAdminBackupFiles,
    SSO_DISCORD_ACTIVE,
    ADMIN_WEB_2FA_ACTIVE,
    SESSION_COOKIE_NAME,
    SESSION_COOKIE_PATH,
    SESSION_COOKIE_SAMESITE,
    SESSION_SECURE_COOKIE,
    SESSION_COOKIE_DOMAIN,
    SESSION_TTL_MS,
    SESSION_IDLE_TIMEOUT_MS,
    SESSION_MAX_PER_USER,
    SESSION_BIND_USER_AGENT,
    ADMIN_WEB_STEP_UP_ENABLED,
    ADMIN_WEB_STEP_UP_TTL_MS,
    ADMIN_WEB_ALLOW_TOKEN_SENSITIVE_MUTATIONS,
  });

  const handleAdminAuthPostRoute = createAdminAuthPostRoutes({
    sendJson,
    requiredString,
    getLoginRateLimitState,
    recordAdminSecuritySignal,
    recordLoginAttempt,
    getUserByCredentials,
    adminWeb2faActive: ADMIN_WEB_2FA_ACTIVE,
    adminWeb2faSecret: ADMIN_WEB_2FA_SECRET,
    adminWeb2faWindowSteps: ADMIN_WEB_2FA_WINDOW_STEPS,
    verifyTotpCode,
    createSession,
    sessionTtlMs: SESSION_TTL_MS,
    buildSessionCookie,
    getSessionId,
    invalidateSession,
    revokeSessionsForUser,
    buildClearSessionCookie,
  });

  const handleAdminCommerceDeliveryPostRoute = createAdminCommerceDeliveryPostRoutes({
    sendJson,
    requiredString,
    asInt,
    parseStringArray,
    getAuthTenantId,
    resolveScopedTenantId,
    listKnownPurchaseStatuses,
    setCoinsExact,
    creditCoins,
    debitCoins,
    addShopItemForAdmin,
    updateShopItemForAdmin,
    setShopItemPriceForAdmin,
    setShopItemStatusForAdmin,
    deleteShopItemForAdmin,
    updatePurchaseStatusForActor,
    queueLeaderboardRefreshForAllGuilds,
    parseDeliveryItemsBody,
    enqueuePurchaseDeliveryByCode,
    retryDeliveryNow,
    retryDeliveryNowMany,
    retryDeliveryDeadLetter,
    retryDeliveryDeadLetterMany,
    removeDeliveryDeadLetter,
    cancelDeliveryJob,
    previewDeliveryCommands,
    getDeliveryPreflightReport,
    simulateDeliveryPlan,
    setDeliveryCommandOverride,
    sendTestDeliveryCommand,
    getDeliveryDetailsByPurchaseCode,
    saveAdminCommandCapabilityPreset,
    getAdminCommandCapabilityPresetById,
    deleteAdminCommandCapabilityPreset,
    testScumAdminCommandCapability,
    runRentBikeMidnightReset,
    getRentBikeRuntime,
    updateScumStatusForAdmin,
    getStatus,
    getTenantFeatureAccess,
    buildTenantProductEntitlements,
    consumeAdminActionRateLimit,
    getClientIp,
  });

  const handleAdminPortalPostRoute = createAdminPortalPostRoutes({
    sendJson,
    ensurePortalTokenAuth,
    readJsonBody,
    requiredString,
    getAuthTenantId,
    redeemCodeForUser,
    requestRentBikeForUser,
    createBountyForUser,
  });

  const handleAdminPlatformPostRoute = createAdminPlatformPostRoutes({
    sendJson,
    prepareTransientDownload,
    requiredString,
    parseStringArray,
    getAuthTenantId,
    resolveScopedTenantId,
    createAdminBackup,
    previewAdminBackupRestore,
    restoreAdminBackup,
    getCurrentObservabilitySnapshot,
    publishAdminLiveUpdate,
    createTenant,
    createPackageCatalogEntry,
    inviteTenantStaff,
    updateTenantStaffRole,
    revokeTenantStaffMembership,
    createServer,
    createServerDiscordLink,
    createSubscription,
    deletePackageCatalogEntry,
    createCheckoutSession,
    updateInvoiceStatus,
    updatePaymentAttempt,
    updateSubscriptionBillingState,
    issuePlatformLicense,
    listPlatformSubscriptions,
    listPlatformLicenses,
    acceptPlatformLicenseLegal,
    createPlatformApiKey,
    createPlatformWebhookEndpoint,
    getServerConfigJob,
    createServerConfigApplyJob,
    createServerConfigRollbackJob,
    createServerConfigSaveJob,
    retryServerConfigJob,
    createServerBotActionJob,
    scheduleRestartPlan,
    createPlatformAgentToken,
    createPlatformAgentProvisioningToken,
    revokePlatformAgentDevice,
    revokePlatformAgentRuntime,
    revokePlatformAgentProvisioningToken,
    revokePlatformAgentToken,
    rotatePlatformAgentToken,
    dispatchPlatformWebhookEvent,
    createMarketplaceOffer,
    reconcileDeliveryState,
    runPlatformMonitoringCycle,
    runPlatformAutomationCycle,
    acknowledgeAdminNotifications,
    clearAdminNotifications,
    getTenantFeatureAccess,
    buildTenantProductEntitlements,
    updatePackageCatalogEntry,
    consumeAdminActionRateLimit,
    getClientIp,
    recordAdminSecuritySignal,
  });

  const handleAdminAuditRoute = createAdminAuditRoutes({
    ensureRole,
    sendJson,
    sendDownload,
    requiredString,
    resolveScopedTenantId,
    readJsonBody,
    buildAuditDatasetService,
    buildAuditExportPayloadService,
    buildAuditCsvService,
    listAuditPresetsService,
    saveAuditPresetService,
    deleteAuditPresetService,
    listAdminSecurityEventsService: listAdminSecurityEvents,
    prisma,
    listEvents: deps.listEvents,
    getParticipants,
    jsonReplacer,
  });

  const { deriveRouteGroup, handleMutationAction } = createAdminRouteRuntime({
    sendJson,
    handleAdminAuthPostRoute,
    handleAdminEntityPostRoute,
    handleAdminConfigPostRoute,
    handleAdminCommerceDeliveryPostRoute,
    handleAdminPortalPostRoute,
    handleAdminPlatformPostRoute,
  });

  return {
    deriveRouteGroup,
    handleMutationAction,
    handleAdminPublicRoute,
    handleAdminGetRoute,
    handleAdminAuthPostRoute,
    handleAdminEntityPostRoute,
    handleAdminConfigPostRoute,
    handleAdminCommerceDeliveryPostRoute,
    handleAdminPortalPostRoute,
    handleAdminPlatformPostRoute,
    handleAdminAuditRoute,
  };
}

module.exports = {
  createAdminRouteHandlersRuntime,
};
