module.exports = {
  apps: [
    {
      name: 'scum-bot-local',
      script: 'src/bot.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'development',
        BOT_ENABLE_SCUM_WEBHOOK: 'true',
        BOT_ENABLE_RESTART_SCHEDULER: 'true',
        BOT_ENABLE_ADMIN_WEB: 'true',
        BOT_ENABLE_RENTBIKE_SERVICE: 'false',
        BOT_ENABLE_DELIVERY_WORKER: 'false',
        BOT_ENABLE_OPS_ALERT_ROUTE: 'true',
        BOT_HEALTH_HOST: '127.0.0.1',
        BOT_HEALTH_PORT: '3210',
      },
    },
    {
      name: 'scum-worker-local',
      script: 'src/worker.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'development',
        WORKER_ENABLE_RENTBIKE: 'true',
        WORKER_ENABLE_DELIVERY: 'true',
        WORKER_HEARTBEAT_MS: '60000',
        WORKER_HEALTH_HOST: '127.0.0.1',
        WORKER_HEALTH_PORT: '3211',
      },
    },
    {
      name: 'scum-watcher-local',
      script: 'src/services/scumLogWatcherRuntime.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'development',
        SCUM_WATCHER_HEALTH_HOST: '127.0.0.1',
        SCUM_WATCHER_HEALTH_PORT: '3212',
      },
    },
    {
      name: 'scum-console-agent-local',
      script: 'src/scum-console-agent.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'development',
        SCUM_CONSOLE_AGENT_HOST: '127.0.0.1',
        SCUM_CONSOLE_AGENT_PORT: '3213',
      },
    },
    {
      name: 'scum-web-portal-local',
      script: 'apps/web-portal-standalone/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'development',
        WEB_PORTAL_SECURE_COOKIE: 'false',
        WEB_PORTAL_ENFORCE_ORIGIN_CHECK: 'true',
      },
    },
  ],
};
