module.exports = {
  apps: [
    {
      name: 'scum-bot',
      script: 'src/bot.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        BOT_ENABLE_SCUM_WEBHOOK: 'true',
        BOT_ENABLE_RESTART_SCHEDULER: 'true',
        BOT_ENABLE_ADMIN_WEB: 'true',
        BOT_ENABLE_RENTBIKE_SERVICE: 'false',
        BOT_ENABLE_DELIVERY_WORKER: 'false',
        BOT_ENABLE_OPS_ALERT_ROUTE: 'true',
        BOT_HEALTH_HOST: '127.0.0.1',
        BOT_HEALTH_PORT: '3210',
      },
    },
    {
      name: 'scum-worker',
      script: 'src/worker.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        WORKER_ENABLE_RENTBIKE: 'true',
        WORKER_ENABLE_DELIVERY: 'true',
        WORKER_HEARTBEAT_MS: '60000',
        WORKER_HEALTH_HOST: '127.0.0.1',
        WORKER_HEALTH_PORT: '3211',
      },
    },
    {
      name: 'scum-web-portal',
      script: 'apps/web-portal-standalone/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        PERSIST_REQUIRE_DB: 'true',
        PERSIST_LEGACY_SNAPSHOTS: 'false',
        ADMIN_SECURITY_EVENT_STORE_MODE: 'db',
        PLATFORM_AUTOMATION_STATE_STORE_MODE: 'db',
        PLATFORM_OPS_STATE_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_STORE_MODE: 'db',
        CONTROL_PLANE_REGISTRY_FILE_MIRROR_SLICES: 'none',
        WEB_PORTAL_SECURE_COOKIE: 'true',
        WEB_PORTAL_ENFORCE_ORIGIN_CHECK: 'true',
      },
    },
    {
      name: 'scum-owner-web',
      script: 'apps/owner-web/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        ADMIN_BACKEND_BASE_URL: 'http://127.0.0.1:3200',
        OWNER_WEB_HOST: '127.0.0.1',
        OWNER_WEB_PORT: '3201',
        TENANT_WEB_BASE_URL: 'http://127.0.0.1:3202',
      },
    },
    {
      name: 'scum-tenant-web',
      script: 'apps/tenant-web/server.js',
      cwd: '.',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        NODE_ENV: 'production',
        PLATFORM_DISCORD_ONLY: 'false',
        ADMIN_BACKEND_BASE_URL: 'http://127.0.0.1:3200',
        TENANT_WEB_HOST: '127.0.0.1',
        TENANT_WEB_PORT: '3202',
        OWNER_WEB_BASE_URL: 'http://127.0.0.1:3201',
      },
    },
  ],
};
