param(
  [string]$ControlPlaneUrl,
  [string]$SetupToken,
  [string]$AgentToken,
  [string]$TenantId,
  [string]$ServerId,
  [string]$DisplayName,
  [string]$ConfigRoot,
  [string]$LogPath,
  [string]$ApplyTemplate,
  [string]$RestartTemplate,
  [string]$RuntimeKey = 'server-bot-main',
  [string]$AgentId = 'server-bot-main',
  [string]$EnvFilePath = '.runtime\server-bot.env',
  [string]$LoaderPath = '.runtime\load-server-bot-env.ps1',
  [string]$HealthHost = '127.0.0.1',
  [int]$HealthPort = 3214,
  [string]$WatcherHealthHost = '127.0.0.1',
  [int]$WatcherHealthPort = 3212,
  [switch]$Production,
  [switch]$DisableWatcher,
  [switch]$StartBot,
  [switch]$Help
)

$ErrorActionPreference = 'Stop'

function Require-Value([string]$Name, [string]$Value) {
  if ([string]::IsNullOrWhiteSpace($Value)) {
    throw "$Name is required"
  }
}

function Escape-SingleQuotes([string]$Value) {
  return ($Value -replace "'", "''")
}

function Format-DotEnvValue([string]$Value) {
  if ($null -eq $Value) {
    return '""'
  }
  $trimmed = [string]$Value
  if ($trimmed -match '^[A-Za-z0-9_:\\/\\.\\-]+$') {
    return $trimmed
  }
  return '"' + ($trimmed -replace '"', '\"') + '"'
}

function Write-Step([string]$Message) {
  Write-Host ""
  Write-Host "[install-server-bot] $Message" -ForegroundColor Cyan
}

function Start-DetachedPowerShell([string]$CommandText) {
  if ([string]::IsNullOrWhiteSpace($CommandText)) {
    return
  }
  Start-Process powershell -ArgumentList @(
    '-NoProfile',
    '-ExecutionPolicy', 'Bypass',
    '-Command', $CommandText
  ) | Out-Null
}

if ($Help) {
  Write-Host 'Usage: powershell -File scripts/install-server-bot.ps1 -ControlPlaneUrl <url> -SetupToken <token>|-AgentToken <token> -TenantId <id> -ServerId <id> -ConfigRoot <path> [options]' -ForegroundColor Yellow
  Write-Host 'Writes a machine-local env file and a reusable PowerShell loader for Server Bot.' -ForegroundColor Yellow
  return
}

Require-Value 'ControlPlaneUrl' $ControlPlaneUrl
Require-Value 'TenantId' $TenantId
Require-Value 'ServerId' $ServerId
Require-Value 'ConfigRoot' $ConfigRoot

$resolvedDisplayName = if ([string]::IsNullOrWhiteSpace($DisplayName)) {
  $AgentId
} else {
  $DisplayName.Trim()
}

if ([string]::IsNullOrWhiteSpace($SetupToken) -and [string]::IsNullOrWhiteSpace($AgentToken)) {
  throw 'Provide SetupToken or AgentToken'
}

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
Set-Location $repoRoot

$resolvedEnvFilePath = Join-Path $repoRoot $EnvFilePath
$resolvedLoaderPath = Join-Path $repoRoot $LoaderPath
$envDir = Split-Path -Parent $resolvedEnvFilePath
$loaderDir = Split-Path -Parent $resolvedLoaderPath

if (-not [string]::IsNullOrWhiteSpace($envDir)) {
  New-Item -ItemType Directory -Force -Path $envDir | Out-Null
}
if (-not [string]::IsNullOrWhiteSpace($loaderDir)) {
  New-Item -ItemType Directory -Force -Path $loaderDir | Out-Null
}

$pairs = [ordered]@{
  'PLATFORM_API_BASE_URL' = $ControlPlaneUrl.TrimEnd('/')
  'SCUM_SYNC_CONTROL_PLANE_URL' = $ControlPlaneUrl.TrimEnd('/')
  'SCUM_TENANT_ID' = $TenantId
  'PLATFORM_TENANT_ID' = $TenantId
  'SCUM_SERVER_ID' = $ServerId
  'PLATFORM_SERVER_ID' = $ServerId
  'SCUM_SERVER_BOT_AGENT_ID' = $AgentId
  'SCUM_SERVER_BOT_RUNTIME_KEY' = $RuntimeKey
  'SCUM_SERVER_BOT_NAME' = $resolvedDisplayName
  'PLATFORM_AGENT_DISPLAY_NAME' = $resolvedDisplayName
  'SCUM_SERVER_CONFIG_ROOT' = $ConfigRoot
  'SCUM_SERVER_BOT_HEALTH_HOST' = $HealthHost
  'SCUM_SERVER_BOT_HEALTH_PORT' = [string]$HealthPort
  'SCUM_WATCHER_ENABLED' = if ($DisableWatcher) { 'false' } else { 'true' }
  'SCUM_WATCHER_HEALTH_HOST' = $WatcherHealthHost
  'SCUM_WATCHER_HEALTH_PORT' = [string]$WatcherHealthPort
  'CONTROL_PLANE_REGISTRY_STORE_MODE' = 'db'
  'PERSIST_REQUIRE_DB' = 'true'
  'PERSIST_LEGACY_SNAPSHOTS' = 'false'
}

if (-not [string]::IsNullOrWhiteSpace($SetupToken)) {
  $pairs['PLATFORM_AGENT_SETUP_TOKEN'] = $SetupToken
}
if (-not [string]::IsNullOrWhiteSpace($AgentToken)) {
  $pairs['PLATFORM_AGENT_TOKEN'] = $AgentToken
}
if (-not [string]::IsNullOrWhiteSpace($LogPath)) {
  $pairs['SCUM_LOG_PATH'] = $LogPath
}
if (-not [string]::IsNullOrWhiteSpace($ApplyTemplate)) {
  $pairs['SCUM_SERVER_APPLY_TEMPLATE'] = $ApplyTemplate
}
if (-not [string]::IsNullOrWhiteSpace($RestartTemplate)) {
  $pairs['SCUM_SERVER_RESTART_TEMPLATE'] = $RestartTemplate
}

$dotenvLines = @(
  '# Generated by scripts/install-server-bot.ps1',
  "# GeneratedAt=$([DateTime]::UtcNow.ToString('o'))"
)
foreach ($entry in $pairs.GetEnumerator()) {
  $dotenvLines += "$($entry.Key)=$(Format-DotEnvValue $entry.Value)"
}

$loaderLines = @(
  '$ErrorActionPreference = ''Stop''',
  '# Generated by scripts/install-server-bot.ps1'
)
foreach ($entry in $pairs.GetEnumerator()) {
  $loaderLines += "`$env:$($entry.Key) = '$(Escape-SingleQuotes ([string]$entry.Value))'"
}
$loaderLines += "Write-Host '[server-bot-env] Environment loaded for $AgentId ($RuntimeKey)' -ForegroundColor Green"

Set-Content -Path $resolvedEnvFilePath -Value ($dotenvLines -join "`r`n") -Encoding utf8
Set-Content -Path $resolvedLoaderPath -Value ($loaderLines -join "`r`n") -Encoding utf8

Write-Step "Wrote server-bot env file"
Write-Host $resolvedEnvFilePath -ForegroundColor Green

Write-Step "Wrote PowerShell loader"
Write-Host $resolvedLoaderPath -ForegroundColor Green

Write-Step 'Validating generated env bundle'
$validationCommand = @(
  'node',
  'scripts/runtime-env-check.js',
  '--role', 'server-bot',
  '--env-file', ('"' + [string]$resolvedEnvFilePath + '"')
)
if ($Production) {
  $validationCommand += '--production'
}
cmd /c ($validationCommand -join ' ')
if ($LASTEXITCODE -ne 0) {
  throw 'Generated server-bot env bundle failed validation'
}

Write-Step 'Next commands'
Write-Host ". $resolvedLoaderPath" -ForegroundColor Yellow
Write-Host 'node apps/server-bot/server.js' -ForegroundColor Yellow
if (-not $DisableWatcher) {
  Write-Host 'node apps/watcher/server.js' -ForegroundColor Yellow
}
Write-Host "node scripts/runtime-env-check.js --role server-bot --env-file `"$resolvedEnvFilePath`"$(if ($Production) { ' --production' } else { '' })" -ForegroundColor Yellow
Write-Host "node scripts/machine-validation.js --role server-bot --production --control-plane-url=$($ControlPlaneUrl.TrimEnd('/'))" -ForegroundColor Yellow
Write-Host "node scripts/runtime-inventory-report.js --role server-bot --tenant-id=$TenantId --server-id=$ServerId" -ForegroundColor Yellow

if ($StartBot) {
  Write-Step 'Starting Server Bot'
  $repoRootQuoted = Escape-SingleQuotes ([string]$repoRoot)
  $loaderQuoted = Escape-SingleQuotes ([string]$resolvedLoaderPath)
  Start-DetachedPowerShell "Set-Location '$repoRootQuoted'; . '$loaderQuoted'; node apps/server-bot/server.js"
  if (-not $DisableWatcher) {
    Start-DetachedPowerShell "Set-Location '$repoRootQuoted'; . '$loaderQuoted'; node apps/watcher/server.js"
  }
  Write-Host 'Server Bot start commands were opened in new PowerShell windows.' -ForegroundColor Green
}
